name:                sweeper
version:             0.1.0.0
github:              "aartamonau/sweeper"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Aliaksei Artamonau"
maintainer:          "aliaksiej.artamonau@gmail.com"
copyright:           "2016-Present Aliaksei Artamonau"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
synopsis:            Haskell playing mine-sweeper
category:            Game
description:         Please see the README on GitHub at <https://github.com/aartamonau/sweeper#readme>

dependencies:
- base
- array
- random
- text
- blank-canvas
- colour
- mtl
- containers
- optparse-applicative
- async
- MonadRandom
- open-browser
- extra
- stm
- stm-delay
- ascii-progress

ghc-options:
- -threaded
- -Wall
- -O2
- -fno-warn-name-shadowing
- -rtsopts
- -with-rtsopts=-N

ghc-prof-options:
- -fprof-auto

default-extensions:
- ApplicativeDo
- BangPatterns
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumDecimals
- OverloadedStrings
- Rank2Types
- RecordWildCards
- StandaloneDeriving
- TupleSections

executables:
  sweeper:
    main:                Main.hs
    source-dirs:         src
